### ISSUE TITLE
Is this library available in Maven Central Repository?

### ISSUE THREAD

**Issue by habina** [bintray/bintray-client-java#9]
Is bintray-client-java available in Maven Central Repository? If yes, I can't find it. I only can find Artifactory Java Client. Thanks.

**Comment by feldan** [comment]
Why not get it from Bintray instead?
https://bintray.com/jfrog/bintray-tools/bintray-client-java

**Comment by seiferma** [comment]
Well, one reason could be that he developed artifacts that shall be pushed to Maven Central. At least when submitting to Sonatype OSS, they [disregard custom repository tags](http://central.sonatype.org/pages/requirements.html#a-complete-example-pom), which would be necessary for users of the artifact. Bintray is no default repository in Maven installations and therefore requires further configuration.

I see three possible solutions:
- You can activate [the sync to Maven Central](https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/).
- You can comment on [my request on Sonatype OSSRH](https://issues.sonatype.org/browse/OSSRH-39008) to submit the client to their repository.
- Every user of your library has to fork it and publish it under his/her own group id.

My favorite is the first option but I can go on with any other option. Just let me know, if you plan to do one of the first two options.

**Comment by seiferma** [comment]
After I received no feedback, I [forked](https://github.com/Cooperate-Project/bintray-client-java) the client and published it to maven central with a different group id. You can use the following dependency if you do not want to use the bintray plugin repository.

```
<dependency>
	<groupId>de.cooperate-project</groupId>
	<artifactId>bintray-client-java-service</artifactId>
	<version>0.9.2</version>
</dependency>
<dependency>
	<groupId>de.cooperate-project</groupId>
	<artifactId>bintray-client-java-api</artifactId>
	<version>0.9.2</version>
</dependency>
```

I have no plans to keep this fork in sync or update the published versions in case of new releases.
